# Generated by Django 2.1.5 on 2019-01-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=200, verbose_name='设备数据')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='接收时间')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='设备名')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='域名')),
                ('city', models.CharField(max_length=10, verbose_name='城市')),
                ('province', models.CharField(max_length=10, null=True, verbose_name='省份')),
                ('country', models.CharField(default='中国', max_length=10, null=True, verbose_name='国家')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.GenericIPAddressField(verbose_name='IP')),
                ('operation', models.CharField(default='IN', max_length=3, verbose_name='操作')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(verbose_name='操作码')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='系统名称')),
                ('platform', models.CharField(default='others', max_length=8, verbose_name='系统平台')),
                ('type', models.CharField(max_length=100, verbose_name='数据模板')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=15, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=40, verbose_name='密码')),
                ('name', models.CharField(max_length=12, verbose_name='昵称')),
                ('phone', models.CharField(max_length=14, unique=True, verbose_name='手机号')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('age', models.PositiveSmallIntegerField(null=True, verbose_name='年龄')),
                ('sex', models.NullBooleanField(verbose_name='性别')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('domain', models.ForeignKey(on_delete='CASCADE', related_name='users', to='SqlMaster.Domain', verbose_name='所属域')),
                ('rely', models.ForeignKey(null=True, on_delete='CASCADE', related_name='sub_user', to='SqlMaster.Users', verbose_name='上级用户')),
                ('system', models.ManyToManyField(related_name='admin', to='SqlMaster.System', verbose_name='子系统')),
            ],
        ),
        migrations.AddField(
            model_name='system',
            name='creatuser',
            field=models.ForeignKey(on_delete='CASCADE', related_name='ownsystem', to='SqlMaster.Users', verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='system',
            name='domain',
            field=models.ForeignKey(on_delete='CASCADE', related_name='system', to='SqlMaster.Domain', verbose_name='所属域'),
        ),
        migrations.AddField(
            model_name='operation',
            name='user',
            field=models.ForeignKey(on_delete='CASCADE', related_name='operation', to='SqlMaster.Users', verbose_name='操作用户'),
        ),
        migrations.AddField(
            model_name='login',
            name='user',
            field=models.ForeignKey(on_delete='CASCADE', related_name='login', to='SqlMaster.Users', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='device',
            name='system',
            field=models.ForeignKey(on_delete='CASCADE', related_name='device', to='SqlMaster.System', verbose_name='所属系统'),
        ),
        migrations.AddField(
            model_name='data',
            name='name',
            field=models.ForeignKey(on_delete='CASCADE', related_name='data', to='SqlMaster.Device', verbose_name='所属设备'),
        ),
    ]
