# Generated by Django 2.1.5 on 2019-01-26 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SqlMaster', '0003_auto_20190123_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='SqlMaster.Device', verbose_name='所属设备'),
        ),
        migrations.AlterField(
            model_name='device',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='SqlMaster.System', verbose_name='所属系统'),
        ),
        migrations.AlterField(
            model_name='login',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login', to='SqlMaster.Users', verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation', to='SqlMaster.Users', verbose_name='操作用户'),
        ),
        migrations.AlterField(
            model_name='system',
            name='createuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownsystem', to='SqlMaster.Users', verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='users',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='SqlMaster.Domain', verbose_name='所属域'),
        ),
        migrations.AlterField(
            model_name='users',
            name='rely',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_user', to='SqlMaster.Users', verbose_name='上级用户'),
        ),
    ]
