# Generated by Django 2.1.5 on 2019-01-27 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SqlMaster', '0005_auto_20190127_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system', to='SqlMaster.Domain', verbose_name='所属域'),
        ),
    ]
