# Generated by Django 2.1.4 on 2018-12-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=200, verbose_name='设备数据')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='接收时间')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='设备名')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='域名')),
                ('address', models.CharField(max_length=50, null=True, unique=True, verbose_name='地址')),
                ('city', models.CharField(max_length=10, null=True, verbose_name='城市')),
                ('province', models.CharField(max_length=10, null=True, verbose_name='省份')),
                ('country', models.CharField(default='中国', max_length=10, null=True, verbose_name='国家')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.GenericIPAddressField(verbose_name='登陆IP')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='登陆时间')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='系统名称')),
                ('type', models.CharField(max_length=100, verbose_name='数据模板')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('domain', models.ForeignKey(on_delete='CASCADE', to='SqlMaster.Domain', verbose_name='所属域')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=15, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=40, verbose_name='密码')),
                ('name', models.CharField(max_length=12, null=True, verbose_name='昵称')),
                ('phone', models.IntegerField(null=True, unique=True, verbose_name='手机号')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='邮箱')),
                ('age', models.IntegerField(null=True, verbose_name='年龄')),
                ('sex', models.NullBooleanField(verbose_name='性别')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('domain', models.ForeignKey(on_delete='CASCADE', to='SqlMaster.Domain', verbose_name='所属域')),
                ('system', models.ManyToManyField(to='SqlMaster.System', verbose_name='子系统')),
            ],
        ),
        migrations.AddField(
            model_name='login',
            name='name',
            field=models.ForeignKey(on_delete='CASCADE', to='SqlMaster.Users', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='device',
            name='system',
            field=models.ForeignKey(on_delete='CASCADE', to='SqlMaster.System', verbose_name='所属系统'),
        ),
        migrations.AddField(
            model_name='data',
            name='name',
            field=models.ForeignKey(on_delete='CASCADE', to='SqlMaster.Device', verbose_name='所属设备'),
        ),
    ]
