# Generated by Django 2.1.3 on 2019-01-30 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SqlMaster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='users',
        ),
    ]
