# Generated by Django 2.1.5 on 2019-01-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SqlMaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(db_index=True, max_length=15, verbose_name='用户名'),
        ),
    ]
