# Generated by Django 2.1.5 on 2019-01-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SqlMaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='platform',
            field=models.CharField(default='others', max_length=8, verbose_name='系统平台'),
        ),
    ]
