# Generated by Django 2.1.5 on 2019-02-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SqlMaster', '0002_remove_device_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='model',
            field=models.BooleanField(default=0, verbose_name='推送/下发'),
        ),
    ]
