# Generated by Django 2.1.4 on 2018-12-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SqlMaster', '0003_auto_20181223_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(verbose_name='操作码')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
        ),
        migrations.RemoveField(
            model_name='opeiation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='domain',
            name='address',
        ),
        migrations.RemoveField(
            model_name='users',
            name='auth',
        ),
        migrations.AddField(
            model_name='users',
            name='rely',
            field=models.ForeignKey(null=True, on_delete='CASCADE', related_name='sub_user', to='SqlMaster.Users', verbose_name='上级用户'),
        ),
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.ForeignKey(on_delete='CASCADE', related_name='data', to='SqlMaster.Device', verbose_name='所属设备'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=30, verbose_name='设备名'),
        ),
        migrations.AlterField(
            model_name='device',
            name='system',
            field=models.ForeignKey(on_delete='CASCADE', related_name='device', to='SqlMaster.System', verbose_name='所属系统'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='city',
            field=models.CharField(max_length=10, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='login',
            name='name',
            field=models.ForeignKey(on_delete='CASCADE', related_name='login', to='SqlMaster.Users', verbose_name='登陆用户'),
        ),
        migrations.AlterField(
            model_name='system',
            name='domain',
            field=models.ForeignKey(on_delete='CASCADE', related_name='system', to='SqlMaster.Domain', verbose_name='所属域'),
        ),
        migrations.AlterField(
            model_name='users',
            name='domain',
            field=models.ForeignKey(on_delete='CASCADE', related_name='users', to='SqlMaster.Domain', verbose_name='所属域'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=12, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.CharField(max_length=14, unique=True, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='users',
            name='system',
            field=models.ManyToManyField(related_name='admin', to='SqlMaster.System', verbose_name='子系统'),
        ),
        migrations.DeleteModel(
            name='Opeiation',
        ),
        migrations.AddField(
            model_name='operation',
            name='user',
            field=models.ForeignKey(on_delete='CASCADE', related_name='operation', to='SqlMaster.Users', verbose_name='操作用户'),
        ),
    ]
