# Generated by Django 2.1.5 on 2019-02-02 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SqlMaster', '0003_data_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='name',
            new_name='device',
        ),
    ]
