# Generated by Django 2.1.5 on 2019-01-27 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SqlMaster', '0004_auto_20190126_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='createuser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ownsystem', to='SqlMaster.Users', verbose_name='创建者'),
        ),
    ]
