# Generated by Django 2.1.5 on 2019-02-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SqlMaster', '0004_auto_20190202_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='type',
            field=models.CharField(default='Other', max_length=100, verbose_name='数据模板'),
        ),
    ]
