# Generated by Django 2.1.5 on 2019-02-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SqlMaster', '0005_auto_20190202_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='platform',
            field=models.CharField(default='Others', max_length=8, verbose_name='系统平台'),
        ),
        migrations.AlterField(
            model_name='system',
            name='type',
            field=models.CharField(max_length=100, verbose_name='数据模板'),
        ),
    ]
