# Generated by Django 2.1.5 on 2019-02-02 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SqlMaster', '0006_auto_20190202_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='system',
            name='key',
        ),
    ]
