# Generated by Django 2.1.5 on 2019-02-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SqlMaster', '0008_data_waring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='waring',
            field=models.NullBooleanField(default=None, verbose_name='正常/异常'),
        ),
    ]
