# Generated by Django 2.1.5 on 2019-02-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SqlMaster', '0009_auto_20190203_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='IMEI',
            field=models.CharField(default='11182131234123', max_length=20, verbose_name='序列号'),
        ),
    ]
