# Generated by Django 2.1.5 on 2019-02-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SqlMaster', '0010_device_imei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='IMEI',
            field=models.CharField(max_length=20, verbose_name='序列号'),
        ),
    ]
