# Generated by Django 2.1.5 on 2019-02-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SqlMaster', '0011_auto_20190203_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='IMEI',
            field=models.CharField(max_length=15, verbose_name='序列号'),
        ),
    ]
