# Generated by Django 2.1.5 on 2019-02-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SqlMaster', '0013_auto_20190210_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='data',
            field=models.CharField(max_length=600, verbose_name='设备数据'),
        ),
        migrations.AlterField(
            model_name='system',
            name='type',
            field=models.CharField(max_length=300, verbose_name='数据模板'),
        ),
    ]
