# Generated by Django 2.1.3 on 2019-04-19 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SqlMaster', '0014_auto_20190213_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='device',
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
