# Generated by Django 2.1.3 on 2019-04-19 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SqlMaster', '0015_auto_20190419_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=600, verbose_name='设备数据')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='接收时间')),
                ('model', models.BooleanField(db_index=True, default=0, verbose_name='订阅/推送')),
                ('waring', models.NullBooleanField(db_index=True, default=None, verbose_name='正常/异常')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='SqlMaster.Device', verbose_name='所属设备')),
            ],
        ),
    ]
